export default {
    FETCH_USERS: 'FETCH_USERS',
    FETCH_USERS_START: 'FETCH_USERS_START',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAIL: 'FETCH_USERS_FAIL',
    FETCH_USER: 'FETCH_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER'
}